config/routes.rb
Rails.application.routes.draw do
  resources :event_users
  resources :users
  resources :events

    get 'create' => 'events#new', as: 'create'

  get '/' => 'events#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users
  has_many :users, through: :event_users

  accepts_nested_attributes_for :users, reject_if: lambda {|attributes| attributes['number'].blank?}, allow_destroy: true
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :event_users
  has_many :events, through: :event_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_users_controller.rb
class EventUsersController < ApplicationController
  before_action :set_event_user, only: [:show, :edit, :update, :destroy]

  # GET /event_users
  # GET /event_users.json
  def index
    @event_users = EventUser.all
  end

  # GET /event_users/1
  # GET /event_users/1.json
  def show
  end

  # GET /event_users/new
  def new
    @event_user = EventUser.new
  end

  # GET /event_users/1/edit
  def edit
  end

  # POST /event_users
  # POST /event_users.json
  def create
    @event_user = EventUser.new(event_user_params)

    respond_to do |format|
      if @event_user.save
        format.html { redirect_to @event_user, notice: 'Event user was successfully created.' }
        format.json { render :show, status: :created, location: @event_user }
      else
        format.html { render :new }
        format.json { render json: @event_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_users/1
  # PATCH/PUT /event_users/1.json
  def update
    respond_to do |format|
      if @event_user.update(event_user_params)
        format.html { redirect_to @event_user, notice: 'Event user was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_user }
      else
        format.html { render :edit }
        format.json { render json: @event_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_users/1
  # DELETE /event_users/1.json
  def destroy
    @event_user.destroy
    respond_to do |format|
      format.html { redirect_to event_users_url, notice: 'Event user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_user
      @event_user = EventUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_user_params
      params.require(:event_user).permit(:status, :user_id, :event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    1.times {@event.users.build}
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :time, :location, :address, :closed, :description, users_attributes: [:number, :name, :_destroy])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :number, :event_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_users/_form.html.erb
<%= form_for(event_user) do |f| %>
  <% if event_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event_user.errors.count, "error") %> prohibited this event_user from being saved:</h2>

      <ul>
      <% event_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.text_field :event_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_users/edit.html.erb
<h1>Editing Event User</h1>

<%= render 'form', event_user: @event_user %>

<%= link_to 'Show', @event_user %> |
<%= link_to 'Back', event_users_path %>

app/views/event_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Users</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>User</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_users.each do |event_user| %>
      <tr>
        <td><%= event_user.status %></td>
        <td><%= event_user.user %></td>
        <td><%= event_user.event %></td>
        <td><%= link_to 'Show', event_user %></td>
        <td><%= link_to 'Edit', edit_event_user_path(event_user) %></td>
        <td><%= link_to 'Destroy', event_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event User', new_event_user_path %>

app/views/event_users/new.html.erb
<h1>New Event User</h1>

<%= render 'form', event_user: @event_user %>

<%= link_to 'Back', event_users_path %>

app/views/event_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @event_user.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @event_user.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event_user.event %>
</p>

<%= link_to 'Edit', edit_event_user_path(@event_user) %> |
<%= link_to 'Back', event_users_path %>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="body">


  <div class="field">
    <% f.label "name" %>
    <%= f.text_field :name, class: "eventname", placeholder: "What"%>
  </div>



  <div class="field">
    <%f.label :When %>
    <%#= f.datetime_select :time %>
    <%= f.text_field :time, class: 'datepicker eventname', placeholder: "When"  %>
  </div>

  <div class="field">
    <% f.label :where%>
    <%= f.text_field :location, placeholder: 'name', class: "eventname", placeholder: "Where" %>
</div>


  <div class="field">
    <% f.label :address %>
    <%= f.text_area :address, placeholder: 'Address', class: "eventname" %>
</div>









    <div class="field">
      <% f.label 'Invite Friends' %>
      <h2>Invite Friends</h2>


  </div>

  <center>

      <%= f.fields_for :users do |users_form|%>
        <%= render partial: 'user_fields', locals: {f: users_form} %>
      <%end%>

<div class="float">
    <%= link_to_add_association "Add More", f, :users, id: 'new-association' %>
</div>
</center>
<div class="containertwo">

    <div class="lefttwo">
      <%= f.check_box :closed%>
  </div>
  <div class="righttwo">
    <%= f.label :closed%>
  </div>
</div><br>
  </div>




<div class="field2">





  <div class="field">
    <% f.label :description %>
    <%= f.text_area :description, class: 'textboxlrg', placeholder:'Description' %>
  </div>

  <div class="actions">
    <%= f.submit(class: 'button') %>
  </div>
</div>
</div>
</div>
<% end %>

<script type="text/javascript">
  flatpickr(".datepicker", {
    enableTime: true,
     dateFormat: "m/d/Y h:m",
     minDate: "today"

  });




  $(document).on('keyup', '.friendfieldnumber', function() {
    var number_values = $('.friendfieldnumber').map(function() { return $(this).val() }).get();
    if ($.inArray('', number_values) == -1) {
      $('#new-association').click();
    }
  })

</script>

app/views/events/_user_fields.erb
<div class="field">
  <%= f.text_field :name, placeholder: 'Name', class: "friendfield friendfieldname" %>
  <%= f.text_field :number, placeholder: 'Phone #', class: "friendfield friendfieldnumber" %>

  <%= link_to_remove_association "X", f %>

</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div class="body">
<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th>Location</th>
      <th>Address</th>
      <th>Closed</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.time %></td>
        <td><%= event.location %></td>
        <td><%= event.address %></td>
        <td><%= event.closed %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<div class="body">
  <h1>What are you planning?</h1>

<%= render 'form', event: @event %>

<% link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<div class="body">
<p id="notice"><%= notice %></p>


  <h1><strong><%= @event.name %></strong></h1>

<div class="field show">
  <strong>When</strong><br>
  <hr>
  <%= @event.time.strftime(('%A, %B %d, %Y @ %H:%M %P')) %><br><br>


  <strong>Where</strong><br>
  <hr>
<%= @event.location %><br>

  <%= @event.address %><br><br>


  <strong>Invite Friends?</strong><br>
  <hr>
  <%= @event.closed %><br><br>



  <strong>More Info</strong><br>
  <hr>

  <%= @event.description %><br><br>




<% link_to 'Edit', edit_event_path(@event) %>
<% link_to 'Back', events_path %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pland</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Pacifico|Quicksand" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
<script src="https://unpkg.com/flatpickr">

</script>

  </head>

  <body>
<header>
  <div class="containermain">
<div class="leftmain">
Pland
</div>

<div class="rightmain">
    <%= link_to '+', create_path %> 
</div>
</div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.text_field :event_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.number %></td>
        <td><%= user.event %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @user.number %>
</p>

<p>
  <strong>Event:</strong>
  <%= @user.event %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>